# Build script for immute attempt
version: '2'

volumes:
    db_data:
    fedora_data:

services:
  isle-mysql:
    build: ./mysql
    # image: islandoracollabgroup/isle-mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ild_mysqlrt_2018
      - MYSQL_ROOT_HOST=172.*.*.*  # This is the default docker network
      # fedora3 ild_feddb_2018 fedora3
      # isle_ld_user isle_ld_db2018 isle_ld
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  isle-fedora:
    build: ./fedora
    # image: islandoracollabgroup/isle-fedora:latest
    container_name: fedora
    ports:
      - "8080:8080"
      - "8777:80"
    tty: true
    depends_on:
      - isle-mysql
      - isle-solr
    volumes:
    - fedora_data:/usr/local/fedora/data
    # - ild_fedora_logs:/usr/local/fedora/server/logs
    # - ild_fedora_apache_logs:/var/log/apache2
    # - ild_fedora_tomcat_logs:/usr/local/tomcat/logs
    

  isle-solr:
    build: ./solr
    # image: islandoracollabgroup/isle-solr:latest
    container_name: solr
    ports:
      - "8091:8080"
      - "8983:8983"
    tty: true
    # volumes:
    # - ild_solr_data:/usr/local/solr/collection1/data
    # - ild_solr_logs:/usr/local/tomcat/logs

  # isle-apache:
  #   build: ./apache
  #   # image: islandoracollabgroup/isle-apache:latest
  #   container_name: apache
  #   environment:
  #     - JAVA_HOME=/usr/lib/jvm/java-8-oracle/
  #     - JRE_HOME=/usr/lib/jvm/java-8-oracle/jre
  #     - PATH="$PATH:$HOME/.composer/vendor/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
  #     - KAKADU_LIBRARY_PATH=/opt/adore-djatoka-1.1/lib/Linux-x86-64
  #     - KAKADU_HOME=/opt/adore-djatoka-1.1/bin/Linux-x86-64
  #   ports:
  #     - "80:80"
  #   tty: true
  #   depends_on:
  #     - isle-mysql
  #     - isle-fedora
  #     - isle-solr
    # volumes:
    #   - isld_apache_data:/var/www/html
    #   - isld_apache_logs:/var/log/apache2
      #- ./isle_localdomain/macosx_settings.php:/var/www/html/sites/default/settings.php
